# Page settings

baseURL = "https://jamescorrenti.github.io"
languageCode = "en"
title = "James Correnti Resume"
theme = "hugo-resume"
googleAnalytics = "G-S3FBXW0Q4L"

[params]
    author = "James Correnti"
    description = "James Correnti - VP of Engineering"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "James Correnti"

        tagline = "VP of Engineering"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "Washington, DC"
        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+1267-402-8260"
        text = "+1 (267) 402-8260"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:james.e.correnti@gmail.com"
        text = "james.e.correnti@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://jamescorrenti.github.io"
        text = "jamescorrenti.github.io"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Programming"
        [[params.skills.list.items]]
        details = "Python, TypeScript, C++, Git"

        [[params.skills.list]]
        title = "DevOps"
        [[params.skills.list.items]]
        details = "AWS, Cloud Developer Kit, CloudFormation, Docker, Kubernetes, CI/CD, Terraform"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Strong problem solver, Engineering leadership and mentorship, Effective communication, Team player"
        
    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS with Honors in Computer Science"
        university = "United States Military Academy"
        dates = "2007 - 2011"
        
    [params.awards]
        enable = false

    [params.languages]
        enable = false


    [params.interests]
        enable = false

    [params.summary]
        enable = true
        text = "Passionate entrepreneur and self-starter, with a distinguished history of transforming visionary engineering concepts into thriving organizations within the federal sector. My journey is marked by a consistent record of steering teams from inception to successful operational stages, demonstrating an exceptional knack for leadership, strategic planning, and a deep understanding of the federal environment. Seeking a technical leadership role in an organization building AI/ML solutions for Federal customers. Currently holds a TS/SCI Clearance with Polygraph."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Cloud Developer"
        dates = "2022 - Present"
        company = "AWS - National Security Professional Services"
        [[params.experience.list.items]]
        details = "Architected and developed a highly flexible and scalable data processing pipeline, designed for deployment across various AWS partitions, including the Top Secret Cloud. This innovation led to a significant efficiency boost for NatSec ProServe's ML practice, reducing the time for consultants to deliver valuable insights to customers by 15%, enhancing customer satisfaction."
        [[params.experience.list.items]]
        details = "Both directed and personally delivered significant technical contributions to an engineering team that developed an AI/ML model security testing framework. This project empowered a key customer's strategic initiative, providing them with the capability to securely test and evaluate models for embedded malware, allowing enhanced client trust in the integrity of their models."        
        [[params.experience.list.items]]
        details = "Recognized as a pivotal security and Cloud Developer Kit (CDK) expert within AWS ProServe teams. Routinely unblocked ProServe teams, ensuring the timely delivery of secure, robust solutions for federal customers."

        [[params.experience.list]]
        title = "Co-Founder and CTO"
        dates = "2018 - 2021"
        company = "Shift5"
        [[params.experience.list.items]]
        details = "Engineered a sophisticated cross-architecture data acquisition and processing pipeline on edge-computing devices customers use to protect critical assets and reduce operating and maintenance costs by 10%."
        [[params.experience.list.items]]
        details = "Reduced production bugs by 20% by designing and implementing an advanced CI/CD pipeline integrated with specialized hardware that enabled unit testing of individual features and integration testing between features and product lines."
        [[params.experience.list.items]]
        details = "Successfully grew and mentored a diverse engineering team, expanding from a sole individual contributor to a robust organization of 20 members, encompassing Data Scientists, Embedded, Platform, Backend, and Frontend Engineers. This growth reflects my strategic leadership in talent development and my commitment to fostering a multidisciplinary team capable of tackling complex technical challenges."
        [[params.experience.list.items]]
        details = "Led a cross-functional team of engineers, product managers, designers, and business stakeholders to create Shift5's core product solutions from initial concepts to installation onto five fleet deployments."       
        
        [[params.experience.list]]
        title = "Cybersecurity Software Engineer"
        dates = "2016 - 2019"
        company = "US Army - Defense Digital Service"
        [[params.experience.list.items]]
        details = "Led efforts to identify and demonstrate cyber vulnerabilities in major weapon systems in the United States Army."
        [[params.experience.list.items]]
        details = "Architected and implemented software that interfaced with an FPGA and software-defined radio product to detect signals emanating from hobby drones and precisely jamming drones, creating a drone-free zone for product operators."
        [[params.experience.list.items]]
        details = "Spearheaded penetration test of secure government network exposing three critical vulnerabilities in the network security model without detection by network defenders leading to an organizational network security transformation to a Zero Trust Architecture. Recognized by the United States Cyber Command for leading this effort and awarded the Joint Service Commendation Medal for meritorious service."

        [[params.experience.list]]
        title = "IT Operations Manager"
        dates = "2014 - 2016"
        company = "US Army - 7th Special Forces Group (Airborne)"
        [[params.experience.list.items]]
        details = "Led cross-functional IT teams with a wide range of skill sets, including Windows System Administration, IT Help Desk, Networking, Cryptography, and Satellite and Radio Communications, conducting support simultaneously on three separate continents in austere environments."

    [params.projects]
        enable = false

    [params.information]
        enable = false

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/jamescorrenti"
        title = "jamescorrenti"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/james-correnti"
        title = "James Correnti"
        [[params.social.list]]
